#!/bin/bash
case $1 in
conf)bash /KivyDexel/config/config.sh;;
dexel)python3 /KivyDexel/main.py;;
cls)clear;;
ins)
case $2 in
git)apt-get install git;;
fish)apt-get install fish
;;
esac
;;
gen)
read -p "What you gonna name this file? " usr_name
touch $usr_name
read -p "What file type is this..(bash,python)? " docker_name
if [ $docker_name = python ]
then
echo "#!/bin/python" >> $usr_name
fi
if [ $docker_name = bash ]
then
echo "#!/bin/bash" >> $usr_name
fi

echo "file generated successfully"
;;
*)echo "
Hi im liz, your docker container's companion..
and you have entered a Invalid Option...
here is a list of commands that i can respond to... ;)
'liz gen' to gen a bash file.
'liz git' to install git.
'liz fish' to install Fish Shell.
'liz conf' to launch config menu.
'liz dexel' to launch Dexel.
'liz cls' to clear terminal.
";;
esac